### ISSUE TITLE
Figure out how to support monthly carbon intensity from Ember

### ISSUE THREAD

**Issue by mrchrisadams** [thegreenwebfoundation/grid-intensity-exporter#10]
Ember is releasing monthly carbon intensity data now.

We currently assume data is updated on an annual basis, and we do some data munging at our end to make sure you can query data by ISO-2 and ISO-3 character country codes.

This is issue is for discussion about how to incorporate monthly data into grid-intensity-go

**Comment by rossf7** [comment]
Closing in favour of https://github.com/thegreenwebfoundation/grid-intensity-go/issues/38

As exporter has moved to grid-intensity-go so this repo can be archived.
