### ISSUE TITLE
Change default provider to Ember dataset

### ISSUE THREAD

**Issue by rossf7** [thegreenwebfoundation/grid-intensity-exporter#7]
Currently the default provider is carbonintensity.org.uk as it doesn't require an API key. However this only supports the UK region.

We will change the default provider to Ember and output metrics for all countries in their 2021 dataset that is embedded in grid-intensity-go. See https://github.com/thegreenwebfoundation/grid-intensity-go/pull/14

```
grid_intensity_carbon_actual{provider="ember-climate.org",region="ESP"} 193.737
```

## Questions

- Do we need to add a label for the year? For the other providers we could use the current year?

```
grid_intensity_carbon_actual{provider="ember-climate.org",region="ESP",year="2021"} 193.737
```

- Ember use 3 char ISO country codes but ElectricityMap and carbonintensity.org.uk use 2 char. Not high priority but should we handle this somehow?

**Comment by rossf7** [comment]
> Yes, I think the year is worth having. Ember have data going back around 20 years, and there are likely folks who would want to backfill

I agree having historic data would be useful. Although it does increase the size of the metrics scraped Prometheus. How about we default to the latest year? But also allow the user to fetch all years by setting an environment variable?

> Yes. I think having a mapping between the two would help. Does Golang have a simple package we would import? If not, I had to build a mapping table with both for a recent carbon intensity feature on the main API, linked below.

There isn't anything for country code mapping in the standard library unfortunately. How about we add the 2 char ISO code to the data file in grid-intensity-go?

We could have either a Makefile or a simple Go program that fetches the latest data from Ember and does any data processing we need? 

We can then create a new release of the grid-intensity CLI with the updated data.

**Comment by mrchrisadams** [comment]
Hi @rossf7 - 

> How about we add the 2 char ISO code to the data file in grid-intensity-go?

Yes. This is the smarter approach IMO. I've added some comments to your open PR to refer to this.

I think anyone doing work with ISO codes would find having both types useful, so it might actually be worth asking for the change upstream. I'll try emailing the nice people at Ember to see if they can add it.

**Comment by rossf7** [comment]
@mrchrisadams Did you hear back from Ember about adding both formats of ISO codes?

Otherwise I have some rough Go code to do this that I can add. It works but it would be simpler if this was in the source data.

I think that's the only thing preventing us closing this issue.

**Comment by mrchrisadams** [comment]
Not yet. Would you mind adding the go code for now, so we can close this off?

Ember is has started publishing data on a monthly basis now, so I think we can revisit things then - which would give us time to ask them to add the 2 and 3 letter country codes

I've made a note in #10 for this.

https://github.com/thegreenwebfoundation/grid-intensity-exporter/issues/10

**Comment by rossf7** [comment]
Yes sure, I'll add the go code.

Good idea to revisit when adding the monthly data. Maybe we can use a similar approach to automate fetching the new data and saving it to the repo.

**Comment by rossf7** [comment]
https://github.com/thegreenwebfoundation/grid-intensity-go/pull/29 Adds the go code and docs on how to run it.
